### ISSUE TITLE
Freedom is too buggy to use...

### ISSUE THREAD

**Issue by scooby78** [scooby78/160th-Frameworks#10]
At this stage, there is no known work around for units falling through invisible cracks and jets rear wheels falling through the deck...  It can be replicated both in dedicated and editor modes...

If anyone finds something post it here..

**Comment by scooby78** [comment]
Post Arma update 1.74:

- Jets now have all wheels fall through deck when engine is tuned off.
- Experienced mass destruction and disassembling of the stern section in official mission.

Not usable in stable missions

**Comment by Nels0** [comment]
USS Freedom overhauled and planes no longer fall through the deck.

Apparently... 

https://dev.arma3.com/post/spotrep-00073

**Comment by scooby78** [comment]
Fixed in 1.76
