### ISSUE TITLE
Rearm pylon function not working in dedicated server environment..

### ISSUE THREAD

**Issue by scooby78** [scooby78/160th-Frameworks#12]
An alternate solution needs to be found..

Ace issue https://github.com/acemod/ACE3/issues/5302 expected to be fixed in  [3.11.0](https://github.com/acemod/ACE3/milestone/30) date unknown

**Comment by Nels0** [comment]
Potential candidate [here](https://www.youtube.com/watch?v=dqFYTUPv6Ww), but given the author hasn't released it yet. His computer was apparently just fried, and so whether Ace fixes the bug or this is MP compatible and releases first is likely a toss-up.

**Comment by scooby78** [comment]
this option seems to take away from the realism going to a virtual system...  Plus yeah, is it MP compatible.. Although I believe the old scripted repair system still works, we might need to go back to that option until its fixed

**Comment by scooby78** [comment]
re added scripted service pad in version K until ACE fixes it

**Comment by scooby78** [comment]
Is being fixed in 3.10.2 which is in RC state ... Repair pads can be removed once confirmed fixed...

**Comment by Nels0** [comment]
I assume this is now fixed, having done this in ACT recently

**Comment by scooby78** [comment]
Confirmed fixed
