### ISSUE TITLE
Confirm Mech vehicles have correct ammo in the framework

### ISSUE THREAD

**Issue by scooby78** [scooby78/160th-Frameworks#16]

**Comment by scooby78** [comment]
SOR_M1A2_TUSKII to have:
M829A3 X20
M830A1 X10
M1028  X6

SOR_M1A2 to have:
M829A3 X20
M830A1 X10
M1069  X6

**Comment by AmTheAgent** [comment]
FYI - When I tried to modify this by Attribs. in the Editor for an Artillery piece you have to be careful - the total it specifies isn't for each ammo type - its for ALL ammo types eg. if max is 40 - that's 40 TOTAL.

**Comment by Nels0** [comment]
Is this still required? Can update in version K
