### ISSUE TITLE
Mission Making Guidelines tweaks

### ISSUE THREAD

**Issue by Nels0** [scooby78/160th-Frameworks#21]
https://github.com/scooby78/160th-Frameworks/wiki

Need consideration:
* AA consideration in briefing (traffic light system)
* TFAR setup
* Signup SOP (who updates what)

**Comment by Nels0** [comment]
from desktruktoid: Zeus Heal
This could be expanded to cover  disallowed modules

**Comment by AmTheAgent** [comment]
Is heal not allowed?

**Comment by scooby78** [comment]
I think this is more directed at "when" it's allowed.

Currently due to the issues from severe vehicle crashes, Zeus heal is allowed once the player has been evacuated back inside the MEV hut.

**Comment by destruktoid** [comment]
Need to add clarification on the utilisation of supports (BS,PJ,Pathfinder) as mentioned in the Mission Discussions thread on steam forum.

**Comment by scooby78** [comment]
I've made some adjustments rule alignment and clarification...  Still needs further updates and revision

**Comment by scooby78** [comment]
crap wrong thread :/

follow :https://github.com/scooby78/160thSOR/issues/48 for further posts
