### ISSUE TITLE
Malden FW - Placement and Asset choice?

### ISSUE THREAD

**Issue by scooby78** [scooby78/160th-Frameworks#9]
I think it should move to the mainland after the deployment.  I'm also not sure about the mixed camo combination with desert units with woodland tanks..  Thoughts?

**Comment by AmTheAgent** [comment]
Ultimately, doesn't matter too much as the Mission builder will likely select which ever he wants anyways. But as a Framework Desert would prob. make more sense

**Comment by scooby78** [comment]
spoke to bean, he's ok with the woodland mech assets

**Comment by scooby78** [comment]
Would there be any objection to the main airfield for relocation after the deployment?

**Comment by scooby78** [comment]
Any takers on making the new base on the mainland?

**Comment by Nels0** [comment]
Can do - will get to it in the next day or two.

**Comment by AmTheAgent** [comment]
Thanks Nelso, Im a bit busy with my Mod, ISIS Mod and Campaign atm!

**Comment by Nels0** [comment]
see: https://github.com/scooby78/160th-Frameworks/pull/18
